[package]
name = "dumbsync"
version = "0.1.0"
authors = ["M*C*O <mcofficer@gmx.de>"]
edition = "2018"

[dependencies]
ureq = {version = "0.12.0", default_features=false, features=["tls"] }
blake3 = "0.3.1"
walkdir = "2"
url = "2.1.1"
pathdiff = "0.1.0"
rayon = "1.1"